apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-project
spec:
  replicas: 1
  selector:
    matchLabels: { app: simple-project }
  template:
    metadata:
      labels: { app: simple-project }
    spec:
      serviceAccountName: demo-app-sa
      containers:
        - name: app
          image: otel-example-project
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 5005
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"